version: '3'
services:
    netbox:
        build:
          context: .
          args:
            - BRANCH=${VERSION-master}
        image: ninech/netbox:${VERSION-latest}
        depends_on:
        - postgres
        env_file: netbox.env
        volumes:
        - ./startup_scripts:/opt/netbox/startup_scripts:ro
        - ./initializers:/opt/netbox/initializers:ro
        - netbox-nginx-config:/etc/netbox-nginx/
        - netbox-static-files:/opt/netbox/netbox/static
        - netbox-media-files:/opt/netbox/netbox/media
        - netbox-report-files:/opt/netbox/netbox/reports
    nginx:
        image: nginx:1.11-alpine
        command: nginx -g 'daemon off;' -c /etc/netbox-nginx/nginx.conf
        depends_on:
        - netbox
        ports:
        - 8080
        volumes:
        - netbox-static-files:/opt/netbox/netbox/static:ro
        - netbox-nginx-config:/etc/netbox-nginx/:ro
    postgres:
        image: postgres:9.6-alpine
        env_file: postgres.env
        volumes:
        - netbox-postgres-data:/var/lib/postgresql/data

volumes:
    netbox-static-files:
        driver: local
    netbox-nginx-config:
        driver: local
    netbox-media-files:
        driver: local
    netbox-report-files:
        driver: local
    netbox-postgres-data:
        driver: local
