blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/netbox-community/netbox-docker/discussions
    about: The Github Discussions are the right place to ask questions about how to use or do certain things with NetBox Docker.

  - name: Chat
    url: https://join.slack.com/t/netdev-community/shared_invite/zt-mtts8g0n-Sm6Wutn62q_M4OdsaIycrQ
    about: "Usually the quickest way to seek help with small issues is to join our #netbox-docker Slack channel."

  - name: Community Wiki
    url: https://github.com/netbox-community/netbox-docker/wiki
    about: |
      Our wiki contains information for common problems and tips for operating NetBox Docker in production.
      It's maintained by our excellent community.
